#!/usr/bin/env bash
# Instructions and commands for installing Nginx on a web server.

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

#testing nginx configurations

sudo nginx -t
sudo service nginx start
