#!/usr/bin/env bash
# Installs Nginx and configures custom HTTP response header

# Update packages
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure custom HTTP response header
header="add_header X-Served-By \$hostname;"
sudo sed -i "s|# server_tokens off;|&\n\t$header|" /etc/nginx/nginx.conf

# Restart Nginx
sudo service nginx restart
