#!/usr/bin/env bash
# Installs and configures HAproxy as a load balancer

# Update packages
sudo apt-get update

# Install HAproxy
sudo apt-get install -y haproxy

# Configure HAproxy
config_file="/etc/haproxy/haproxy.cfg"

# Backup the original configuration file
sudo cp $config_file $config_file.bak

# Clear the existing configuration and add new configuration
sudo tee $config_file > /dev/null <<EOT
frontend lb-frontend
    bind *:80
    mode http
    default_backend lb-backend

backend lb-backend
    mode http
    balance roundrobin
    server  206553-web-01 54.144.133.171:80 check
    server  206553-web-02 52.201.221.140:80 check
EOT

# Enable HAproxy init script
sudo sed -i 's/^ENABLED=.*/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy
sudo service haproxy restart
