#!/usr/bin/env bash
# This script automates the installation and configuration of HAProxy
sudo apt-get update -y
sudo apt-get install -y haproxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo touch /etc/haproxy/haproxy.cfg
sudo chmod 666 /etc/haproxy/haproxy.cfg

echo "global
		log /dev/log	local0
		log /dev/log	local1 notice
		chroot /var/lib/haproxy
		stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
		stats timeout 30s
		user haproxy
		group haproxy
		daemon
		
defaults
		log		global
		mode	http
		option	httplog
		option	dontlognull
		timeout	connect 5000
		timeout	client 	50000
		timeout	server	50000

frontend http-in
		bind *:80
		default_backend servers

backend servers
		balance	roundrobin
		server	206553-web-01 54.144.133.171:80 check
		server	206553-web-02 52.201.221.140:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart
