#!/usr/bin/env bash
# Using your previous exercise command, writing a Bash script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# Displays a list of currently running processes containing the bash keyword.

ps -aux | grep bash
