#!/usr/bin/env bash
# Executes the "whoami" command, taking the user provided as an argument.
if [ $# -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

user=$1
whoami_output=$(sudo -u "$user" whoami)
echo "$whoami_output"
