#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
grep -rli "127.0.0.1" /etc/nginx/sites-available/ | xargs sed -i "s/127.0.0.1/0.0.0.0/g"
service nginx restart
